version: "3"
services:
  pg:
    image: postgres:14-alpine
    environment:
      - POSTGRES_PASSWORD=password
  pgadmin:
    image: dpage/pgadmin4:7
    ports:
      - "5050:80"
    entrypoint: >
      /bin/sh -c "
      cp -f /pgadmin4/pgpass /var/lib/pgadmin/;
      chmod 600 /var/lib/pgadmin/pgpass;
      chown pgadmin:pgadmin /var/lib/pgadmin/pgpass;
      /entrypoint.sh
      "
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
      - PGADMIN_CONFIG_SERVER_MODE=False
      - PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED=False
    depends_on:
      - pg
    volumes:
      - ./servers.json:/pgadmin4/servers.json
      - ./pgpass:/pgadmin4/pgpass
  redis:
    image: redis/redis-stack:latest
    volumes:
      - "redis:/data"
    ports:
      - "6379:6379"
      - "8001:8001"
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/usr/src/app
    ports:
      - "3000:3000"
    depends_on:
      - pg
      - redis
    environment:
      - REDIS_URL=redis://redis:6379/0
      - POSTGRES_HOST=pg
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PASSWORD=password

volumes:
  redis:
  postgres:
